### ISSUE TITLE
Disk image processor not recognizing HFS-formatted disk images

### ISSUE THREAD

**Issue by KyleDennis03** [CCA-Public/cca-tools#3] opened 2020-11-23 15:13 UTC
I recently imaged a box of 3.5" floppies using Kryoflux. The disks were said to be Mac-formatted and the log files created by Disk image processor and Kryoflux both confirmed that the images were HFS format. 

**The Problem:** When I tried to extract files from these disk images using Disk image processor, all I got out of any of them was this one file called "Desktop" that was 0B. According to the log file generated in this process, the file is not a disk image, and is skipped. Naturally, I then tried HFS Explorer to see if that would do anything, but I got the exact same "Desktop" file that had a timestamp from 1990. I then tried FTK and got nothing, not even the empty Desktop file.

~~Another peculiar issue with these disks is that even though they're supposedly Mac-formatted, Kryoflux does not recognize them if they are imaged using the seemingly appropriate image profile of Apple DOS 400K/800K sector image. The only way that I was able to get a properly formatted image was by using the MFM sector image profile, which does not make sense to me. Could that be the cause of these problems?
I've enclosed copies of the Disk image processor log file, as well as the log file from one of the disk images made on Kryoflux, if this helps clarify anything.~~ Disregard that, I just noticed that the MFM image profile is for any **high-density** floppy disks, which is what these are. I simply confused them for **double-density** floppies.

I've enclosed copies of the Disk image processor log file, as well as the log file from one of the disk images made on Kryoflux, if this helps clarify anything.

If anyone can help, we would greatly appreciate it! Thank you.

[COS_DM_01_01.log](https://github.com/CCA-Public/cca-tools/files/5583893/COS_DM_01_01.log)
[diskimageprocessor.log](https://github.com/CCA-Public/cca-tools/files/5583901/diskimageprocessor.log)

**Comment by tw4l** [comment] 2021-06-18 16:47
Closing this for now, as I believe the issue is particular to these disk images (maybe they were in fact empty?), since HFS Explorer was also unable see any content beyond an empty Desktop file.

If anyone has a similar issue and can provide additional information, feel free to re-open.

**Closed as completed by tw4l** 2021-06-18 16:47 UTC
